@startuml "Generated"
' hide stereotype
legend
|<back:AliceBlue><b>Linux Server   </b></back>|
|<back:LightGreen><b>Docker Container</b></back>|
|<back:SeaShell><b>Docker Network    </b></back>|
endlegend

	node  "kiwano" as kiwano #AliceBlue {

		component "\nweblogic\ncasasprod:10252021\ncasasprod" as casasprod #LightGreen {

	}
		component "\nweblogic\naprprod19c:11182021\naprprod" as aprprod #LightGreen {

	}
		component "\napache\nhousingelements:04022021\nd9679392be45" as d9679392be45 #LightGreen {

	}
		component "\nwildfly\nhousingelements:07172021\n92139934823c" as 92139934823c #LightGreen {

	}
		component "\napache\ncasasprod\n2e9eee224cd1" as 2e9eee224cd1 #LightGreen {

	}
		component "\napache\naprprod:12032020\n19561b8ea54f" as 19561b8ea54f #LightGreen {

	}
		component "\nweaveworks\nscope:1.8.0\nkiwano.hcd.ca.gov" as kiwano.hcd.ca.gov #LightGreen {

	}
		component "\nsolarwinds\norion:v3_stable\n121066bf5bf9" as 121066bf5bf9 #LightGreen {

	}
		component "\nweblogic\ncasasapi:12042020\ncasasprod" as casasprod #LightGreen {

	}
}
@enduml