@startuml "Generated"
'on: 2021-12-28T12:38:34.477-08:00
'hide stereotype

legend
|<back:AliceBlue><b>Linux Server   </b></back>|
|<back:LightGreen><b>Docker Container</b></back>|
|<back:SeaShell><b>Docker cloud     </b></back>|
|<back:Yellow><b>File System Folder </b></back>|
endlegend

	component "\npumpkin" as x136404212 #AliceBlue {
	

		node "\n/nofaapache" as x51798953 #LightGreen {
	
			cloud  "Ports" as p1 #SeaShell  {
                "3000/tcp\n443/tcp\n80/tcp\n"
            }

			folder "Bindings" as b1 #Yellow {
            "/opt/accelerator/drupalfiles/webform/mdap/:/var/www/html/acceleratorfiles\n/opt/homekey/drupalfiles/webform/homekey_application:/var/www/html/homekeyfiles\n/opt/nofa/apache/logs:/var/log/httpd\n/opt/nofa/drupalfiles/webform/nova_form:/var/www/html/nofafiles\n/opt/nofa/webroot:/var/www/html\n"
            }

	    }

		node "\n/acceleratordevapache" as x81443005 #LightGreen {
	

			cloud  "Ports" as p2 #SeaShell {
                "443/tcp\n80/tcp\n"
}

			folder "Bindings" as b2 #Yellow {
"/opt/acceleratordev/drupalfiles:/var/www/drupalfiles\n/opt/acceleratordev/sync:/var/www/content/sync/\n/opt/acceleratordev/webroot/:/var/www/html/\n"
}

 

}
@enduml