@startuml "SuperNOFA on Pumpkin"
'on: 2022-01-20T13:58:52.811-08:00
' hide stereotype
legend
|<back:AliceBlue><b>Linux Server         </b></back>|
'|<back:LightGreen><b>Docker Container   </b></back>|
'|<back:SeaShell><b>Docker Network       </b></back>|
|<back:GreenYellow><b>File System Folder </b></back>|
|<back:Khaki><b>Non-Docker Component     </b></back>|
|<back:Gold><b>Database                  </b></back>|
|<back:LightGreen><b>Deployed App        </b></back>|

 
endlegend

 

	component "\npumpkin" as x136404212 #AliceBlue {

       card "https://nofadfa.hcd.ca.gov/snap" as url 

        folder   "/opt/tomcat" as ftomcat #GreenYellow {
             card "tomcat config, logs, etc."
	        folder   "temp/ab-434" as fab #GreenYellow {
                card "Location of uploaded attachments"
            }
        }


		node "\ntomcat" as ntomcat #Khaki {

            

			cloud "Ports" as xporsttomcat #SeaShell {
			card "8080/tcp\n" as pval745
            }

            component "ab434\nReact Web UI (javascript)"  as cabr #LightGreen {

                
            }
            url -> cabr

			component "superNofaApi.war\nSpring Boot (java) back-end"  as cwar #LightGreen {			
			}

            cabr <-> cwar

	}

    ftomcat  --[hidden]-- ntomcat
	 ' ntomcat  --[hidden]-- ftomcat
    
    cwar ..> fab :writes attachments to
    ntomcat ..> ftomcat :uses

	
    component "MySQL Server\n" as cdb #Khaki {

          database "\nsupernofa" as ddb #Gold {
            card "user 'humanyu'" as dbuser 
            cloud "Ports" as dbport #SeaShell {
			card "8306/tcp\n" 
            }
         }
    }

    cwar ..> ddb :stores data in




}



@enduml