@startuml "nofadfa network on pumpkin"
'!theme sketchy-outline
hide stereotype

'skinparam linetype ortho

legend
|<back:AliceBlue><b>Linux Server   </b></back>|
|<back:LightGreen><b>Docker Container</b></back>|
|<back:SeaShell><b>Docker Network    </b></back>|
endlegend

'title "HCD DEV/TEST Web/Drupal Deployment" 
   
   node "pumpkin\nOracle Linux 8.5" <<i>> as pumpkin8 #AliceBlue {

    ''''folders'''''

    folder "/opt" as fopt #AliceBlue { 
        folder "nofa" as foptnofa #AliceBlue {    
        
            folder "keycloak" as foptnofakey  #AliceBlue {     
            }
            folder "drupal" as foptnofadr  #AliceBlue {     
            }
            folder "wildfly" as foptnofawild  #AliceBlue {     
            }
           folder "mysql" as foptnofasqld  #AliceBlue {     
            }
        }
        folder "accelerator" as foptacc  #AliceBlue {     
        }
        folder "homekey" as fopthk  #AliceBlue {     
        }
    }
    
    '''''cloud'''''
    cloud "nofadfa\n" #SeaShell {
   
    component "nofaapache\n165.235.4.61:80\nApache" as nofaap #LightGreen {  
    }

    nofaap ..> foptacc :mounts
    nofaap ..> foptnofa :mounts
    nofaap ..> fopthk :mounts

    component "nofadfa\n165.235.4.61:8080\nJBoss WildFly" as nofawf #LightGreen {
      
    }

    nofawf ..> foptnofawild :mounts
    nofawf ..> fopthk :mounts
    nofawf ..> foptacc :mounts
    nofawf ..> foptnofadr :mounts

    component "keycloakd\n165.235.4.61:8443\nJBoss WildFly" as nofakc #LightGreen {
    }  
    nofakc ..> foptnofakey :mounts
  
    'cloud "nofadfa"
  }  
     
  cloud "bridge\n" #SeaShell {
    database "mysql\n165.235.4.124:8306\nMySql Server" as dbnofa #LightGreen {
    }  
      
    dbnofa ..> foptnofasqld :mounts
    }
}

@enduml
