@startuml "Generated"
'on: 2022-01-20T13:58:52.811-08:00
' hide stereotype
legend
|<back:AliceBlue><b>Linux Server   </b></back>|
|<back:LightGreen><b>Docker Container</b></back>|
|<back:SeaShell><b>Docker Network    </b></back>|
|<back:Yellow><b>File System Folder </b></back>|
|<back:Khaki><b>Non-Dockerized</b></back>|
 
endlegend

	component "\npumpkin" as x136404212 #AliceBlue {
	

		node "\n/w3uatapache" as x212689061 #LightGreen {
	

			cloud "Ports" as ports958 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval135
}

			frame "Bindings"  as bind770 #Yellow {
			card "/opt/w3uat/drupalfiles:/var/www/drupalfiles\n/opt/w3uat/sync:/var/www/content/sync/\n/opt/w3uat/webroot/:/var/www/html/\n" as cval968
			}

	}

	 

		node "\n/w3devapache" as x227844470 #LightGreen {
	

			cloud "Ports" as ports808 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval895
}

			frame "Bindings"  as bind407 #Yellow {
			card "/opt/w3dev/drupalfiles:/var/www/drupalfiles\n/opt/w3dev/sync:/var/www/content/sync/\n/opt/w3dev/webroot/:/var/www/html/\n" as cval304
			}

	}

		node "\n/homekeydevapache" as x237945370 #LightGreen {
	

			cloud "Ports" as ports892 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval745
}

			frame "Bindings"  as bind260 #Yellow {
			card "/opt/homekeydev/apache/logs:/var/log/httpd\n/opt/homekeydev/content:/var/www/content/\n/opt/homekeydev/drupalfiles:/var/www/drupalfiles\n/opt/homekeydev/webroot/:/var/www/html/\n" as cval71
			}

	}

	 

		node "\n/acceleratordevapache" as x81443005 #LightGreen {
	

			cloud "Ports" as ports979 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval622
}

			frame "Bindings"  as bind343 #Yellow {
			card "/opt/acceleratordev/drupalfiles:/var/www/drupalfiles\n/opt/acceleratordev/sync:/var/www/content/sync/\n/opt/acceleratordev/webroot/:/var/www/html/\n" as cval535
			}

	}


		node "\n/homekeyapache" as x111235695 #LightGreen {
	

			cloud "Ports" as ports939 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval644
}

			frame "Bindings"  as bind864 #Yellow {
			card "/opt/homekey/apache/logs:/etc/httpd/logs\n/opt/homekey/content:/var/www/content/\n/opt/homekey/drupalfiles:/var/www/drupalfiles\n/opt/homekey/webroot/:/var/www/html/\n" as cval116
			}

	}

	 

	 
x212689061 -[hidden]- x227844470
x227844470 -[hidden]-  x237945370
x237945370 -[hidden]- x81443005
x81443005 -[hidden]- x111235695
 

}

 component "\ngrapes" as xgrapes #AliceBlue {

     component "MySQL Server\n" as xgrsql #Khaki {

          database "\naccelerator" as xaccb #Gold {
            card "user 'plato1'" as cval111 #Yellow
         }


 
         database "\ndrupal9" as xd9b #Gold {
            card "user 'rahim'" as cval112 #Yellow
         }

        xaccb -[hidden]- xd9b

         database "\nhomekey10" as xhk10b #Gold {

                 card "user 'plato2'" as cval113 #Yellow        
         }

         xd9b -[hidden]- xhk10b

         database "\nhomekey20" as xhk20b #Gold {

                 card "user 'plato3'" as cval114 #Yellow             
         
         }
        
        xhk10b -[hidden]- xhk20b

         database "\nw3prod" as xw3prodb  #Gold {

                 card "user 'plato4'" as cval115 #Yellow             
         }
        xhk20b -[hidden]- xw3prodb
        
        database "\nw3prod10" as xw3prod10b #Gold {

                 card "user 'plato5'" as cval1236 #Yellow            
         }

        xw3prodb -[hidden]- xw3prod10b
     }

 }


@enduml