@startuml

partition Requestor {
    (*) --> [find the PDF form] "Create Request"
    "Create Request" --> [fill out the form] "Submit Request"
    "Submit Request" --> [submit]  "Email (First) Approver"
    "Close Request" -down-> (*)
    "Start Executing" --> (*)
}

partition "Approvals" {

    "Request Denied" --> "Close Request"
    "Request Approved" --> "Start Executing"

    partition "Approver" {
        "Email (First) Approver" --> [notify] "Make a Decision"    
        if "denied?" then
            -right-> [deny] "Request Denied"
        else
            if "approved?" then
                if "last approver?" then
                    --> [yes]  "Request Approved"
                else     
                    --> [no] "Email Next Approver"
                endif
            endif
        endif
    }
    "Email Next Approver" ..> [next approver] "Make a Decision"
}

@enduml