@startuml


partition Executor {
    "Execute Request" -down-> [executed] (*)
}

partition "Approvals Workflow" {
    "Determine Next Step" --> [approved] "Determine Next Approver"
    "Determine Next Step" --> [rejected] "Close Request"
    "Close Request" -down-> (*)
    "Determine Next Step" ..> [all approved] "Execute Request"
}


partition Approver {
    "Determine Next Approver" -right-> [notify] "Make a Decision"
    "Make a Decision" ..> [decision made] "Determine Next Step"
}

partition Requestor {
    (*) --> "Create Request"
    "Create Request" --> [add info] "Edit Request"
    "Edit Request" --> [submit] "Determine Next Step"
    "Determine Next Step" --> [more info requested] "Edit Request"
    
}

@enduml