@startuml "Generated"
'on: 2021-12-28T13:44:24.553-08:00
' hide stereotype
legend
|<back:AliceBlue><b>Linux Server   </b></back>|
|<back:LightGreen><b>Docker Container</b></back>|
|<back:SeaShell><b>Docker Network    </b></back>|
|<back:Yellow><b>File System Folder </b></back>|
endlegend

	component "\nkiwano" as x174654613 #AliceBlue {
	

		node "\n/housingelements" as x216975557 #LightGreen {
	

			cloud "Ports" as ports25 #SeaShell {
			card "8080/tcp\n" as pval353
}

			frame "Bindings"  as bind871 #Yellow {
			card "/opt/housingelements/wildfly/logs/server.log:/opt/jboss/wildfly/standalone/log/server.log\n" as cval396
			}

	}

		node "\n/aprprod" as x174926803 #LightGreen {
	

			cloud "Ports" as ports470 #SeaShell {
			card "7001/tcp\n7002/tcp\n8001/tcp\n8002/tcp\n8453/tcp\n" as pval589
}

			frame "Bindings"  as bind894 #Yellow {
			card "/opt/aprprod/weblogic/apr_uploaded_files:/u01/oracle/user_projects/domains/aprprod/apr_uploaded_files\n/opt/aprprod/weblogic/logs/apradmin.log:/u01/oracle/user_projects/domains/aprprod/servers/apradmin/logs/apradmin.log\n/opt/aprprod/weblogic/logs/aprprod.log:/u01/oracle/user_projects/domains/aprprod/servers/apradmin/aprprod.log\n/opt/aprprod/weblogic/properties/docker-run:/u01/oracle/properties\n" as cval3
			}

	}

		node "\n/housingelementsapache" as x31121023 #LightGreen {
	

			cloud "Ports" as ports794 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval475
}

			frame "Bindings"  as bind120 #Yellow {
			card "/opt/housingelements/apache/logs:/var/log/httpd\n" as cval550
			}

	}

		node "\n/aprprodapache" as x27926429 #LightGreen {
	

			cloud "Ports" as ports591 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval963
}

	}

		node "\n/casasprod" as x201186995 #LightGreen {
	

			cloud "Ports" as ports232 #SeaShell {
			card "7001/tcp\n7002/tcp\n8001/tcp\n8002/tcp\n8453/tcp\n" as pval421
}

			frame "Bindings"  as bind887 #Yellow {
			card "/opt/casasprod/weblogic/UPLOADS/CASAS_FILES/:/u01/oracle/UPLOADS/CASAS_FILES/\n/opt/casasprod/weblogic/blobs/hcdletters/:/u01/oracle/blobs/hcdletters/\n/opt/casasprod/weblogic/blobs/repreceipts/:/u01/oracle/blobs/repreceipts/\n/opt/casasprod/weblogic/logs/access.log:/u01/oracle/user_projects/domains/casasprod/servers/casasadmin/logs/access.log\n/opt/casasprod/weblogic/logs/casasadmin.log:/u01/oracle/user_projects/domains/casasprod/servers/casasadmin/logs/casasadmin.log\n/opt/casasprod/weblogic/properties/docker-run:/u01/oracle/properties\n" as cval741
			}

	}

		node "\n/recovercaapache" as x26784587 #LightGreen {
	

			cloud "Ports" as ports788 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval195
}

	}

		node "\n/casasprodapache" as x264905597 #LightGreen {
	

			cloud "Ports" as ports398 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval202
}

	}

		node "\n/weaveworks_scope" as x120489002 #LightGreen {
	

			frame "Bindings"  as bind69 #Yellow {
			card "/var/run/docker.sock:/var/run/docker.sock:rw\n" as cval733
			}

	}

		node "\n/orion-orionaggregator" as x185970893 #LightGreen {
	

			cloud "Ports" as ports921 #SeaShell {
			card "4043/tcp\n" as pval891
}

			frame "Bindings"  as bind476 #Yellow {
			card "solarwinds_cman-volume:/swdata:rw\n" as cval265
			}

	}

		node "\n/casasapi" as x20523776 #LightGreen {
	

			cloud "Ports" as ports666 #SeaShell {
			card "7001/tcp\n7002/tcp\n8001/tcp\n8002/tcp\n8453/tcp\n" as pval672
}

			frame "Bindings"  as bind540 #Yellow {
			card "/opt/casasprod/weblogicAPI/CASAS_FILES_PROD/:/u01/oracle/CASAS_FILES_PROD/\n/opt/casasprod/weblogicAPI/logs/casasadmin.log:/u01/oracle/user_projects/domains/casasprod/servers/casasadmin/logs/casasadmin.log\n/opt/casasprod/weblogicAPI/properties/docker-run:/u01/oracle/properties\n" as cval450
			}

	}
x216975557 -[hidden]- x174926803
x174926803 -[hidden]- x31121023
x31121023 -[hidden]- x27926429
x27926429 -[hidden]- x201186995
x201186995 -[hidden]- x26784587
x26784587 -[hidden]- x264905597
x264905597 -[hidden]- x120489002
x120489002 -[hidden]- x185970893
x185970893 -[hidden]- x20523776

}
@enduml