@startuml "Generated"
'on: 2021-12-28T13:45:37.377-08:00
' hide stereotype
legend
|<back:AliceBlue><b>Linux Server   </b></back>|
|<back:LightGreen><b>Docker Container</b></back>|
|<back:SeaShell><b>Docker Network    </b></back>|
|<back:Yellow><b>File System Folder </b></back>|
endlegend

	component "\npumpkin" as x136404212 #AliceBlue {
	

		node "\n/nofaapache" as x51798953 #LightGreen {
	

			cloud "Ports" as ports248 #SeaShell {
			card "3000/tcp\n443/tcp\n80/tcp\n" as pval689
}

			frame "Bindings"  as bind460 #Yellow {
			card "/opt/accelerator/drupalfiles/webform/mdap/:/var/www/html/acceleratorfiles\n/opt/homekey/drupalfiles/webform/homekey_application:/var/www/html/homekeyfiles\n/opt/nofa/apache/logs:/var/log/httpd\n/opt/nofa/drupalfiles/webform/nova_form:/var/www/html/nofafiles\n/opt/nofa/webroot:/var/www/html\n" as cval866
			}

	}

		node "\n/acceleratordevapache" as x81443005 #LightGreen {
	

			cloud "Ports" as ports745 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval350
}

			frame "Bindings"  as bind226 #Yellow {
			card "/opt/acceleratordev/drupalfiles:/var/www/drupalfiles\n/opt/acceleratordev/sync:/var/www/content/sync/\n/opt/acceleratordev/webroot/:/var/www/html/\n" as cval955
			}

	}

		node "\n/homekeydevapache" as x237945370 #LightGreen {
	

			cloud "Ports" as ports51 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval264
}

			frame "Bindings"  as bind86 #Yellow {
			card "/opt/homekeydev/content:/var/www/content/\n/opt/homekeydev/drupalfiles:/var/www/drupalfiles\n/opt/homekeydev/webroot/:/var/www/html/\n" as cval294
			}

	}

		node "\n/w3uatapache" as x212689061 #LightGreen {
	

			cloud "Ports" as ports987 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval374
}

			frame "Bindings"  as bind751 #Yellow {
			card "/opt/w3uat/drupalfiles:/var/www/drupalfiles\n/opt/w3uat/sync:/var/www/content/sync/\n/opt/w3uat/webroot/:/var/www/html/\n" as cval562
			}

	}

		node "\n/w3devapache" as x227844470 #LightGreen {
	

			cloud "Ports" as ports891 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval5
}

			frame "Bindings"  as bind698 #Yellow {
			card "/opt/w3dev/drupalfiles:/var/www/drupalfiles\n/opt/w3dev/sync:/var/www/content/sync/\n/opt/w3dev/webroot/:/var/www/html/\n" as cval779
			}

	}

		node "\n/nofadfa" as x11793698 #LightGreen {
	

			cloud "Ports" as ports109 #SeaShell {
			card "8080/tcp\n9990/tcp\n" as pval545
}

			frame "Bindings"  as bind665 #Yellow {
			card "/opt/accelerator/drupalfiles/webform/mdap/:/opt/jboss/wildfly/welcome-content/accelerator\n/opt/homekey/drupalfiles/webform/homekey_application:/opt/jboss/wildfly/welcome-content/homekey\n/opt/nofa/drupalfiles/webform/nova_form:/opt/jboss/wildfly/welcome-content/calhomeDisaster\n/opt/nofa/wildfly/logs/:/opt/jboss/wildfly/standalone/log/\n" as cval502
			}

	}

		node "\n/keycloakd" as x140374474 #LightGreen {
	

			cloud "Ports" as ports369 #SeaShell {
			card "8080/tcp\n8443/tcp\n" as pval338
}

			frame "Bindings"  as bind880 #Yellow {
			card "/opt/nofa/keycloak/data:/opt/jboss/keycloak/standalone/data/\n" as cval562
			}

	}

		node "\n/nofaappdb" as x4480958 #LightGreen {
	

			cloud "Ports" as ports637 #SeaShell {
			card "3306/tcp\n33060/tcp\n33061/tcp\n" as pval361
}

			frame "Bindings"  as bind784 #Yellow {
			card "/nofaapp/mysql/conf.d:/etc/mysql/conf.d\n/nofaapp/mysql/log:/var/log\n/nofaapp/mysql/mysql-data:/var/lib/mysql\n" as cval481
			}

	}

		node "\n/homekeyapache" as x111235695 #LightGreen {
	

			cloud "Ports" as ports711 #SeaShell {
			card "443/tcp\n80/tcp\n" as pval381
}

			frame "Bindings"  as bind40 #Yellow {
			card "/opt/homekey/apache/logs:/etc/httpd/logs\n/opt/homekey/content:/var/www/content/\n/opt/homekey/drupalfiles:/var/www/drupalfiles\n/opt/homekey/webroot/:/var/www/html/\n" as cval410
			}

	}

		node "\n/mysql-hcdwebsite" as x242279748 #LightGreen {
	

			cloud "Ports" as ports925 #SeaShell {
			card "3306/tcp\n33060/tcp\n33061/tcp\n" as pval637
}

			frame "Bindings"  as bind655 #Yellow {
			card "/hcdwebsite/mysql/conf.d:/etc/mysql/conf.d\n/hcdwebsite/mysql/log:/var/log\n/hcdwebsite/mysql/mysql-data:/var/lib/mysql\n" as cval1
			}

	}

		node "\n/mysql-hcddeloitte" as x143529167 #LightGreen {
	

			cloud "Ports" as ports590 #SeaShell {
			card "3306/tcp\n33060/tcp\n33061/tcp\n" as pval553
}

			frame "Bindings"  as bind679 #Yellow {
			card "/hcddeloitte/mysql/conf.d/my.cnf:/etc/my.cnf\n/hcddeloitte/mysql/log:/var/log\n/hcddeloitte/mysql/mysql-data:/var/lib/mysql\n" as cval573
			}

	}
x51798953 -[hidden]- x81443005
x81443005 -[hidden]- x237945370
x237945370 -[hidden]- x212689061
x212689061 -[hidden]- x227844470
x227844470 -[hidden]- x11793698
x11793698 -[hidden]- x140374474
x140374474 -[hidden]- x4480958
x4480958 -[hidden]- x111235695
x111235695 -[hidden]- x242279748
x242279748 -[hidden]- x143529167

}
@enduml